apiVersion: skaffold/v2alpha3
kind: Config
deploy:
  kubectl:
    manifests:
      - ./infra/k8s/*
build:
  # # build the docker image locally and do not push it to registry
  # local:
  #   push: false
  googleCloudBuild:
    projectId: ticketing-416906
  artifacts:
    - image: us.gcr.io/ticketing-416906/auth
      # # local image
      # image: dmsehuang/ticketing-auth
      context: auth
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: 'src/**/*.ts'
            dest: .
    - image: us.gcr.io/ticketing-416906/client
      context: client
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: '**/*.js'
            dest: .
